name: Lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v7
      - name: yamllint
        id: yamllint
        continue-on-error: true
        run: |
          pipx run yamllint -c yamllint.yml config/ 2>&1 | tee yamllint_output.txt
      - name: Comment PR on failure
        if: steps.yamllint.outcome == 'failure'
        uses: https://code.thetadev.de/actions/comment-pull-request@v1
        with:
          filePath: yamllint_output.txt
          comment_tag: yamllint-report
      - name: Fail job if yamllint failed
        if: steps.yamllint.outcome == 'failure'
        run: exit 1
