collections: []
metadata:
  Cowboy Bebop:
    url_poster: https://theposterdb.com/api/assets/69930
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/127307
  Dragon Ball DAIMA:
    url_poster: https://theposterdb.com/api/assets/526434
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/526435
  FLCL:
    url_poster: https://theposterdb.com/api/assets/168809
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/181197
      2:
        url_poster: https://theposterdb.com/api/assets/181198
      3:
        url_poster: https://theposterdb.com/api/assets/181199
  "Food Wars!":
    url_poster: https://theposterdb.com/api/assets/69024
    seasons:
      4:
        url_poster: https://theposterdb.com/api/assets/69028
      5:
        url_poster: https://theposterdb.com/api/assets/130013
  Mobile Suit Gundam:
    url_poster: https://theposterdb.com/api/assets/1501
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/140597
  My Hero Academia:
    url_poster: https://theposterdb.com/api/assets/47852
    seasons:
      4:
        url_poster: https://theposterdb.com/api/assets/47857
      5:
        url_poster: https://theposterdb.com/api/assets/140415
  One-Punch Man:
    url_poster: https://theposterdb.com/api/assets/124176
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/74931
      2:
        url_poster: https://theposterdb.com/api/assets/74932
  Super Dragon Ball Heroes:
    url_poster: https://theposterdb.com/api/assets/127796
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/127820
      2:
        url_poster: https://theposterdb.com/api/assets/127821
      3:
        url_poster: https://theposterdb.com/api/assets/127822
      4:
        url_poster: https://theposterdb.com/api/assets/140889
  Dragon Ball GT:
    url_poster: https://theposterdb.com/api/assets/127784
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/127815
      2:
        url_poster: https://theposterdb.com/api/assets/127817
      3:
        url_poster: https://theposterdb.com/api/assets/127819
  Sailor Moon:
    url_poster: https://theposterdb.com/api/assets/157095
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/343711
      2:
        url_poster: https://theposterdb.com/api/assets/343712
  Yu Yu Hakusho:
    url_poster: https://theposterdb.com/api/assets/100471
    seasons:
      Specials:
        url_poster: https://theposterdb.com/api/assets/254487
      1:
        url_poster: https://theposterdb.com/api/assets/100473
      2:
        url_poster: https://theposterdb.com/api/assets/100474
      3:
        url_poster: https://theposterdb.com/api/assets/100475
      4:
        url_poster: https://theposterdb.com/api/assets/100476
