collections: []
metadata:
  Cowboy Bebop:
    url_poster: https://theposterdb.com/api/assets/69930
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/127307
  Dragon Ball DAIMA:
    url_poster: https://theposterdb.com/api/assets/526434
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/526435
  FLCL:
    url_poster: https://theposterdb.com/api/assets/407633
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/407634
      2:
        url_poster: https://theposterdb.com/api/assets/407635
      3:
        url_poster: https://theposterdb.com/api/assets/407636
      4:
        url_poster: https://theposterdb.com/api/assets/407637
      5:
        url_poster: https://theposterdb.com/api/assets/419863
  Mobile Suit Gundam:
    url_poster: https://theposterdb.com/api/assets/140595
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/140597
  One-Punch Man:
    url_poster: https://theposterdb.com/api/assets/312223
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/312225
      2:
        url_poster: https://theposterdb.com/api/assets/312226
  Dragon Ball GT:
    url_poster: https://theposterdb.com/api/assets/127784
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/127815
      2:
        url_poster: https://theposterdb.com/api/assets/127817
      3:
        url_poster: https://theposterdb.com/api/assets/127819
  Sailor Moon:
    url_poster: https://theposterdb.com/api/assets/157095
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/343711
      2:
        url_poster: https://theposterdb.com/api/assets/343712
  Yu Yu Hakusho:
    url_poster: https://theposterdb.com/api/assets/100471
    seasons:
      Specials:
        url_poster: https://theposterdb.com/api/assets/254487
      1:
        url_poster: https://theposterdb.com/api/assets/100473
      2:
        url_poster: https://theposterdb.com/api/assets/100474
      3:
        url_poster: https://theposterdb.com/api/assets/100475
      4:
        url_poster: https://theposterdb.com/api/assets/100476
