settings:
  custom_repo: https://github.com/ImDevinC/plex-meta-manager-configs
plex:
  url: http://plex-ct.collins.home:32400
  token: ${PMM_PLEX_TOKEN}
tmdb:
  apikey: ${PMM_TMDB_TOKEN}
  language: en
libraries:
  Movies:
    metadata_path:
      - repo: /main/config/movies
    delete_unmanaged_collections: true
    operations:
      metadata_backup:
        path: /source/movies-backup.yml
        add_blank_entries: true
  TV Shows:
    metadata_path:
      - repo: /main/config/tv
  Anime:
    metadata_path:
      - repo: /main/config/anime
radarr:
  url: http://radarr:7878/radarr
  token: ${PMM_RADARR_TOKEN}
  add: false
  monitor: true
  search: true
  quality_profile: HD - 720p/1080p
  root_folder_path: /movies