default_template:
  tmdb_collection_details: <<value>>
  minimum_items: 3

templates:
  studio:
    optional: [company]
    tmdb_company: <<company>>
    sync_mode: sync
    smart_label: release.desc
    sort_title: +5_<<collection_name>>
    collection_mode: hide
  director:
    smart_filter:
      all:
        director: tmdb
      sort_by: year.asc
    tmdb_person: <<person>>
    sort_title: +3_1_<<collection_name>
    collection_mode: hide
collections:
  A24 Collection:
    template: {name: studio, company: 41077}
    summary: A24 is an American independent entertainment company founded on August 20, 2012, by Daniel Katz, David Fenkel, and John Hodges and based in New York City. It specializes in film distribution, and film and television production.
    url_poster: https://theposterdb.com/api/assets/49079
  View Askew Collection:
    template: {name: studio, company: 16934}
    summary: View Askew Productions is an American film and television production company founded by Kevin Smith and Scott Mosier in 1994.
    url_poster: https://theposterdb.com/api/assets/47526
  Studio Ghibli Collection:
    template: {name: studio, company: 10342}
    summary: Studio Ghibli Inc. is a Japanese animation film studio headquartered in Koganei, Tokyo. It is best known for its animated feature films, and has also produced several short subjects, television commercials, and two television films.
    url_poster: https://theposterdb.com/api/assets/67350
  Disney Animated Collection:
    template: {name: studio, company: 6125}
    summary: Walt Disney Animation Studios is an American animation studio that creates animated features and short films for The Walt Disney Company.
    url_poster: https://theposterdb.com/api/assets/103270
  "MCU: Infinity Saga":
    letterboxd_list: https://letterboxd.com/imdevinc/list/mcu-infinity-saga/
    collection_order: custom
    sync_mode: sync
    url_poster: https://theposterdb.com/api/assets/29314
  "MCU: Multiverse Saga":
    letterboxd_list: https://letterboxd.com/imdevinc/list/mcu-multiverse-saga/
    collection_order: custom
    sync_mode: sync
dynamic_collections:
  "TMDB Collections":
    type: tmdb_collection
