collections: []
metadata:
  Arrested Development:
    url_poster: https://theposterdb.com/api/assets/46402
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/46403
      2:
        url_poster: https://theposterdb.com/api/assets/46404
      3:
        url_poster: https://theposterdb.com/api/assets/46405
      4:
        url_poster: https://theposterdb.com/api/assets/46406
      5:
        url_poster: https://theposterdb.com/api/assets/46407
  "Avatar: The Last Airbender":
    url_poster: https://theposterdb.com/api/assets/58044
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/58046
      2:
        url_poster: https://theposterdb.com/api/assets/58047
      3:
        url_poster: https://theposterdb.com/api/assets/58048
  Better Off Ted:
    url_poster: https://www.themoviedb.org/t/p/w600_and_h900_bestv2/u6QkbGwjH0qtGO6Cz9fFi6BxRi2.jpg
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/9803
      2:
        url_poster: https://theposterdb.com/api/assets/9804
  Brooklyn Nine-Nine:
    url_poster: https://theposterdb.com/api/assets/169390
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/173152
      2:
        url_poster: https://theposterdb.com/api/assets/173153
      3:
        url_poster: https://theposterdb.com/api/assets/173154
      4:
        url_poster: https://theposterdb.com/api/assets/173155
      5:
        url_poster: https://theposterdb.com/api/assets/173156
      6:
        url_poster: https://theposterdb.com/api/assets/173157
      7:
        url_poster: https://theposterdb.com/api/assets/173158
      8:
        url_poster: https://theposterdb.com/api/assets/173159
  Community:
    url_poster: https://theposterdb.com/api/assets/160357
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/65084
      2:
        url_poster: https://theposterdb.com/api/assets/65085
      3:
        url_poster: https://theposterdb.com/api/assets/65086
      4:
        url_poster: https://theposterdb.com/api/assets/65087
      5:
        url_poster: https://theposterdb.com/api/assets/65088
      6:
        url_poster: https://theposterdb.com/api/assets/65089
  The League:
    url_poster: https://theposterdb.com/api/assets/127295
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/127296
      2:
        url_poster: https://theposterdb.com/api/assets/127297
      3:
        url_poster: https://theposterdb.com/api/assets/127298
      4:
        url_poster: https://theposterdb.com/api/assets/127299
      5:
        url_poster: https://theposterdb.com/api/assets/127300
      6:
        url_poster: https://theposterdb.com/api/assets/127301
      7:
        url_poster: https://theposterdb.com/api/assets/127302
  My Name Is Earl:
    url_poster: https://theposterdb.com/api/assets/267109
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/265533
      2:
        url_poster: https://theposterdb.com/api/assets/265534
      3:
        url_poster: https://theposterdb.com/api/assets/265535
      4:
        url_poster: https://theposterdb.com/api/assets/265536
  New Girl:
    url_poster: https://theposterdb.com/api/assets/112879
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/112880
      2:
        url_poster: https://theposterdb.com/api/assets/112882
      3:
        url_poster: https://theposterdb.com/api/assets/112883
      4:
        url_poster: https://theposterdb.com/api/assets/112885
      5:
        url_poster: https://theposterdb.com/api/assets/112887
      6:
        url_poster: https://theposterdb.com/api/assets/112889
      7:
        url_poster: https://theposterdb.com/api/assets/112891
  Psych:
    url_poster: https://theposterdb.com/api/assets/88617
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/88619
      2:
        url_poster: https://theposterdb.com/api/assets/88620
      3:
        url_poster: https://theposterdb.com/api/assets/88621
      4:
        url_poster: https://theposterdb.com/api/assets/88622
      5:
        url_poster: https://theposterdb.com/api/assets/88623
      6:
        url_poster: https://theposterdb.com/api/assets/88624
      7:
        url_poster: https://theposterdb.com/api/assets/88625
      8:
        url_poster: https://theposterdb.com/api/assets/88626
  Pushing Daisies:
    url_poster: https://theposterdb.com/api/assets/103381
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/160113
      2:
        url_poster: https://theposterdb.com/api/assets/160114
  Raising Hope:
    url_poster: https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uoQlWrYVERlifyUjDVUHiSu2ELo.jpg
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/253020
      2:
        url_poster: https://theposterdb.com/api/assets/253021
      3:
        url_poster: https://theposterdb.com/api/assets/253022
      4:
        url_poster: https://theposterdb.com/api/assets/253023
  Rick and Morty:
    url_poster: https://theposterdb.com/api/assets/29456
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/47885
      2:
        url_poster: https://theposterdb.com/api/assets/47886
      3:
        url_poster: https://theposterdb.com/api/assets/47887
      4:
        url_poster: https://theposterdb.com/api/assets/47888
      5:
        url_poster: https://theposterdb.com/api/assets/156005
  The Righteous Gemstones:
    url_poster: https://theposterdb.com/api/assets/138364
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/138365
      2:
        url_poster: https://theposterdb.com/api/assets/199688
  Silicon Valley:
    url_poster: https://theposterdb.com/api/assets/19793
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/19801
      2:
        url_poster: https://theposterdb.com/api/assets/19802
      3:
        url_poster: https://theposterdb.com/api/assets/19804
      4:
        url_poster: https://theposterdb.com/api/assets/19805
      5:
        url_poster: https://theposterdb.com/api/assets/19807
      6:
        url_poster: https://theposterdb.com/api/assets/29968
  Ted Lasso:
    url_poster: https://theposterdb.com/api/assets/164299
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/175954
      2:
        url_poster: https://theposterdb.com/api/assets/175955
  Superstore:
    url_poster: https://theposterdb.com/api/assets/136622
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/267012
      2:
        url_poster: https://theposterdb.com/api/assets/267013
      3:
        url_poster: https://theposterdb.com/api/assets/267014
      4:
        url_poster: https://theposterdb.com/api/assets/267015
      5:
        url_poster: https://theposterdb.com/api/assets/267016
      6:
        url_poster: https://theposterdb.com/api/assets/141360
  Scrubs:
    url_poster: https://theposterdb.com/api/assets/246096
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/43008
      2:
        url_poster: https://theposterdb.com/api/assets/43009
      3:
        url_poster: https://theposterdb.com/api/assets/43010
      4:
        url_poster: https://theposterdb.com/api/assets/43011
      5:
        url_poster: https://theposterdb.com/api/assets/43012
      6:
        url_poster: https://theposterdb.com/api/assets/43013
      7:
        url_poster: https://theposterdb.com/api/assets/43014
      8:
        url_poster: https://theposterdb.com/api/assets/43015
      9:
        url_poster: https://theposterdb.com/api/assets/43016
  "Parks and Recreation":
    url_poster: https://theposterdb.com/api/assets/125115
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/125117
      2:
        url_poster: https://theposterdb.com/api/assets/125118
      3:
        url_poster: https://theposterdb.com/api/assets/125119
      4:
        url_poster: https://theposterdb.com/api/assets/125120
      5:
        url_poster: https://theposterdb.com/api/assets/125121
      6:
        url_poster: https://theposterdb.com/api/assets/125122
      7:
        url_poster: https://theposterdb.com/api/assets/268506
  "Scott Pilgrim Takes Off":
    url_poster: https://theposterdb.com/api/assets/433051
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/433049
  The Office (US):
    url_poster: https://theposterdb.com/api/assets/139508
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/139509
      2:
        url_poster: https://theposterdb.com/api/assets/139510
      3:
        url_poster: https://theposterdb.com/api/assets/139511
      4:
        url_poster: https://theposterdb.com/api/assets/139512
      5:
        url_poster: https://theposterdb.com/api/assets/139513
      6:
        url_poster: https://theposterdb.com/api/assets/139514
      7:
        url_poster: https://theposterdb.com/api/assets/139515
      8:
        url_poster: https://theposterdb.com/api/assets/139516
      9:
        url_poster: https://theposterdb.com/api/assets/139517
  Yu Yu Hakusho:
    url_poster: https://theposterdb.com/api/assets/443416
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/443417
