name: Comment Action

on:
  issue_comment:

jobs:
  issue_commented:
    name: Issue Comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install yq
        run: sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod a+x /usr/local/bin/yq
      - name: Add Movie
        run: ./add_movie.sh "${{ github.event.issue.title }}" "${{ github.event.comment.body }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "[CI] Added ${{ github.event.issue.title}}"
          commit_message: "[CI] Added ${{ github.event.issue.title}}"
          branch: "feat-auto-${{ github.event.comment.id }}"
          base: main